# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-15 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_iban.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('sur_name', models.CharField(default='', max_length=250)),
                ('iban', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34, unique=True)),
                ('concatenado', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
