# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-15 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='sur_name',
            new_name='surname',
        ),
    ]
